#!/bin/env python3

import sys
import os
import re
import sys
import pprint

import argparse

import utils
from generic_fn import GenericFn
from task import Task

"""
$ python3 preprocessor [-d] --input_file <input_file> --output_file <output_file> --task <task to generate the export function>

E.g.

python3 preprocessor --input_file test_shake256_32_64.jpp --output_file test_shake256_32_64.jpp --task "fn:shake256 p:OUTLEN:32 p:INLEN:64"
"""

def parse_args():
    parser = argparse.ArgumentParser(description="Jasmin source code preprocessor")

    parser.add_argument(
        "--input_file",
        required=True,
        help="Input file path",
        type=str,
    )

    parser.add_argument(
        "--output_file",
        required=True,
        help="Output file path",
        type=str,
    )

    parser.add_argument(
        "-d",
        "--debug",
        help="Enable debugging",
        action="store_true",  # Makes -d a flag without an argument
    )

    parser.add_argument("--task", required=False, nargs="+")

    return parser.parse_args()


def resolve_templates(
    text: str,
    global_params: dict[str, int],
    generic_fn_dict: dict[str, GenericFn],
    debug: bool,
) -> str:
    """
    Resolves templates in the source code.
    The code assumes that all template declarations follow the format
    '[inline] fn <function_name><template_params>(<parameters>) -> <return_type> { <function_body> } //<>'
    """
    # 1st step: Update global params dict. The source file may define new `param int` variables or override previously
    #           defined ones
    tmp: dict[str, int] = utils.get_params(text)
    global_params.update(tmp)

    # 2nd step: Update generic functions dict from Jasmin source code
    tmp: dict[str, GenericFn] = utils.get_generic_fn_dict(text)
    generic_fn_dict.update(tmp)

    # 3rd step: Remove the code of the generic functions from the source code
    text = utils.remove_generic_fn_text(text)

    # 4th step: Replace calls to generic functions with calls to concrete functions
    text = utils.replace_generic_calls_with_concrete(text, global_params)

    # 5th step: Get a list of all the tasks that need to be done
    # First, we gather the tasks without handling nested calls, and then, after all
    # the tasks are collected, resolve the nested calls in the Task class.
    # This needs to be done on the input_text instead of the already processed text
    tasks: list[Task] = export_tasks + utils.get_tasks(input_text, global_params)

    if debug:
        print("\n\nTasks [1st pass]:")
        pprint.pprint(tasks)

    if debug:
        print("\n\nSearching for subtasks")

    for task in tasks:
        subtasks = task.get_sub_tasks(generic_fn_dict)
        tasks.extend(subtasks)

    if debug:
        print("\n\nTasks [2nd pass (includes subtasks)]:")
        pprint.pprint(tasks)

    # Remove duplicate tasks
    # tasks = list(set(tasks))
    tasks = utils.remove_duplicates(tasks)

    if debug:
        print("\n\nTasks [3rd pass (removes duplicate tasks)]:")
        pprint.pprint(tasks)

    # 6th step: Resolve each task
    for task in tasks:
        text = task.resolve(text, generic_fn_dict)

    # 7th step: Resolve generic function calls that were not resolved before
    text = utils.replace_expression_in_call(text)  # Evaluates expressions inside <>
    text = re.sub(
        r"(\w+)<([^>]+)>",
        lambda match: f"{match.group(1)}_{'_'.join(str(global_params.get(p.strip(), p.strip())) for p in match.group(2).split(','))}",
        text,
    )

    # Last step: Remove extra blank space & remove auxiliary comments
    pattern = r"// Place concrete instances of the (\w+) function here"
    text = re.sub(pattern, "", text)

    pattern = r"\n{3,}"
    while re.search(pattern, text):
        text = re.sub(pattern, "\n\n", text)

    text = text.strip()

    return text


if __name__ == "__main__":
    args = parse_args()

    # Check if the input files exists
    if not os.path.exists(args.input_file):
        sys.stderr.write(f"Error: The file '{args.input_file}' does not exist.\n")
        sys.exit(-1)

    with open(args.input_file, "r") as f:
        text: str = f.read()

    # 1st step: Load global parameters from param files
    global_params: dict[str, int] = utils.get_params(text)

    # 2nd step: Get generic functions dict from Jasmin source code
    generic_fn_dict: dict[str, GenericFn] = utils.get_generic_fn_dict(text)

    export_tasks: [Task] = utils.parse_tasks(args.task, global_params, generic_fn_dict)

    if args.debug:
        print("DEBUG: Global Param Dictionary")
        pprint.pprint(global_params)
        print("\n\nDEBUG: Generic Fn Dictionary:")
        pprint.pprint(generic_fn_dict.keys())

    with open(args.input_file, "r") as f:
        input_text: str = f.read()

    output_text: str = resolve_templates(
        input_text, global_params, generic_fn_dict, args.debug
    )
    output_text += "\n"

    if args.debug:
        print("\n--------------------------------------------------------------\n")

    with open(args.output_file, "w") as f:
        f.write(output_text)
